#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 174
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 76
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  sym__letter = 1,
  sym__oct = 2,
  sym__dec = 3,
  anon_sym_0 = 4,
  aux_sym__dec_lit_token1 = 5,
  sym__hex = 6,
  anon_sym_X = 7,
  anon_sym_x = 8,
  anon_sym_ = 9,
  anon_sym_2 = 10,
  aux_sym__ident_token1 = 11,
  anon_sym_SQUOTE = 12,
  aux_sym__single_string_token1 = 13,
  anon_sym_DQUOTE = 14,
  aux_sym__double_string_token1 = 15,
  anon_sym_COLON = 16,
  anon_sym_SEMI = 17,
  anon_sym_COMMA = 18,
  anon_sym_LBRACK = 19,
  anon_sym_RBRACK = 20,
  sym_comment = 21,
  anon_sym_LBRACE = 22,
  anon_sym_RBRACE = 23,
  anon_sym_LT = 24,
  anon_sym_GT = 25,
  anon_sym_SLASH = 26,
  anon_sym_DOT = 27,
  anon_sym_DASH = 28,
  anon_sym_F = 29,
  anon_sym_f = 30,
  anon_sym_E = 31,
  anon_sym_e = 32,
  anon_sym_PLUS = 33,
  sym_source_file = 34,
  sym__dec_lit = 35,
  sym__oct_int = 36,
  sym__hex_int = 37,
  sym__ident = 38,
  sym_identifier = 39,
  sym__single_string = 40,
  sym__double_string = 41,
  sym_scalar_field = 42,
  sym_scalar_list = 43,
  sym__field = 44,
  sym_message_field = 45,
  sym_message_list = 46,
  sym_message_value = 47,
  sym_field_name = 48,
  sym_extension_name = 49,
  sym_any_name = 50,
  sym_type_name = 51,
  sym_domain = 52,
  sym__scalar_value = 53,
  sym_string = 54,
  sym_float = 55,
  sym_signed_identifier = 56,
  sym_dec_signed_integer = 57,
  sym_oct_signed_integer = 58,
  sym_hex_signed_integer = 59,
  sym_dec_unsigned_integer = 60,
  sym_oct_unsigned_integer = 61,
  sym_hex_unsigned_integer = 62,
  sym__string = 63,
  sym__float = 64,
  sym__dec_int = 65,
  sym_float_lit = 66,
  sym__exp = 67,
  aux_sym_source_file_repeat1 = 68,
  aux_sym__dec_lit_repeat1 = 69,
  aux_sym__oct_int_repeat1 = 70,
  aux_sym__hex_int_repeat1 = 71,
  aux_sym_scalar_list_repeat1 = 72,
  aux_sym_message_list_repeat1 = 73,
  aux_sym_type_name_repeat1 = 74,
  aux_sym_string_repeat1 = 75,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__letter] = "_letter",
  [sym__oct] = "_oct",
  [sym__dec] = "_dec",
  [anon_sym_0] = "0",
  [aux_sym__dec_lit_token1] = "_dec_lit_token1",
  [sym__hex] = "_hex",
  [anon_sym_X] = "X",
  [anon_sym_x] = "x",
  [anon_sym_] = "",
  [anon_sym_2] = "\f",
  [aux_sym__ident_token1] = "_ident_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__single_string_token1] = "_single_string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__double_string_token1] = "_double_string_token1",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_comment] = "comment",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_SLASH] = "/",
  [anon_sym_DOT] = ".",
  [anon_sym_DASH] = "-",
  [anon_sym_F] = "F",
  [anon_sym_f] = "f",
  [anon_sym_E] = "E",
  [anon_sym_e] = "e",
  [anon_sym_PLUS] = "+",
  [sym_source_file] = "source_file",
  [sym__dec_lit] = "_dec_lit",
  [sym__oct_int] = "_oct_int",
  [sym__hex_int] = "_hex_int",
  [sym__ident] = "_ident",
  [sym_identifier] = "identifier",
  [sym__single_string] = "_single_string",
  [sym__double_string] = "_double_string",
  [sym_scalar_field] = "scalar_field",
  [sym_scalar_list] = "scalar_list",
  [sym__field] = "_field",
  [sym_message_field] = "message_field",
  [sym_message_list] = "message_list",
  [sym_message_value] = "message_value",
  [sym_field_name] = "field_name",
  [sym_extension_name] = "extension_name",
  [sym_any_name] = "any_name",
  [sym_type_name] = "type_name",
  [sym_domain] = "domain",
  [sym__scalar_value] = "_scalar_value",
  [sym_string] = "string",
  [sym_float] = "float",
  [sym_signed_identifier] = "signed_identifier",
  [sym_dec_signed_integer] = "dec_signed_integer",
  [sym_oct_signed_integer] = "oct_signed_integer",
  [sym_hex_signed_integer] = "hex_signed_integer",
  [sym_dec_unsigned_integer] = "dec_unsigned_integer",
  [sym_oct_unsigned_integer] = "oct_unsigned_integer",
  [sym_hex_unsigned_integer] = "hex_unsigned_integer",
  [sym__string] = "_string",
  [sym__float] = "_float",
  [sym__dec_int] = "_dec_int",
  [sym_float_lit] = "float_lit",
  [sym__exp] = "_exp",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__dec_lit_repeat1] = "_dec_lit_repeat1",
  [aux_sym__oct_int_repeat1] = "_oct_int_repeat1",
  [aux_sym__hex_int_repeat1] = "_hex_int_repeat1",
  [aux_sym_scalar_list_repeat1] = "scalar_list_repeat1",
  [aux_sym_message_list_repeat1] = "message_list_repeat1",
  [aux_sym_type_name_repeat1] = "type_name_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__letter] = sym__letter,
  [sym__oct] = sym__oct,
  [sym__dec] = sym__dec,
  [anon_sym_0] = anon_sym_0,
  [aux_sym__dec_lit_token1] = aux_sym__dec_lit_token1,
  [sym__hex] = sym__hex,
  [anon_sym_X] = anon_sym_X,
  [anon_sym_x] = anon_sym_x,
  [anon_sym_] = anon_sym_,
  [anon_sym_2] = anon_sym_2,
  [aux_sym__ident_token1] = aux_sym__ident_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__single_string_token1] = aux_sym__single_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__double_string_token1] = aux_sym__double_string_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_F] = anon_sym_F,
  [anon_sym_f] = anon_sym_f,
  [anon_sym_E] = anon_sym_E,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_source_file] = sym_source_file,
  [sym__dec_lit] = sym__dec_lit,
  [sym__oct_int] = sym__oct_int,
  [sym__hex_int] = sym__hex_int,
  [sym__ident] = sym__ident,
  [sym_identifier] = sym_identifier,
  [sym__single_string] = sym__single_string,
  [sym__double_string] = sym__double_string,
  [sym_scalar_field] = sym_scalar_field,
  [sym_scalar_list] = sym_scalar_list,
  [sym__field] = sym__field,
  [sym_message_field] = sym_message_field,
  [sym_message_list] = sym_message_list,
  [sym_message_value] = sym_message_value,
  [sym_field_name] = sym_field_name,
  [sym_extension_name] = sym_extension_name,
  [sym_any_name] = sym_any_name,
  [sym_type_name] = sym_type_name,
  [sym_domain] = sym_domain,
  [sym__scalar_value] = sym__scalar_value,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [sym_signed_identifier] = sym_signed_identifier,
  [sym_dec_signed_integer] = sym_dec_signed_integer,
  [sym_oct_signed_integer] = sym_oct_signed_integer,
  [sym_hex_signed_integer] = sym_hex_signed_integer,
  [sym_dec_unsigned_integer] = sym_dec_unsigned_integer,
  [sym_oct_unsigned_integer] = sym_oct_unsigned_integer,
  [sym_hex_unsigned_integer] = sym_hex_unsigned_integer,
  [sym__string] = sym__string,
  [sym__float] = sym__float,
  [sym__dec_int] = sym__dec_int,
  [sym_float_lit] = sym_float_lit,
  [sym__exp] = sym__exp,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__dec_lit_repeat1] = aux_sym__dec_lit_repeat1,
  [aux_sym__oct_int_repeat1] = aux_sym__oct_int_repeat1,
  [aux_sym__hex_int_repeat1] = aux_sym__hex_int_repeat1,
  [aux_sym_scalar_list_repeat1] = aux_sym_scalar_list_repeat1,
  [aux_sym_message_list_repeat1] = aux_sym_message_list_repeat1,
  [aux_sym_type_name_repeat1] = aux_sym_type_name_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__letter] = {
    .visible = false,
    .named = true,
  },
  [sym__oct] = {
    .visible = false,
    .named = true,
  },
  [sym__dec] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__dec_lit_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__hex] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_X] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__ident_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__single_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__double_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_F] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__dec_lit] = {
    .visible = false,
    .named = true,
  },
  [sym__oct_int] = {
    .visible = false,
    .named = true,
  },
  [sym__hex_int] = {
    .visible = false,
    .named = true,
  },
  [sym__ident] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__single_string] = {
    .visible = false,
    .named = true,
  },
  [sym__double_string] = {
    .visible = false,
    .named = true,
  },
  [sym_scalar_field] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_list] = {
    .visible = true,
    .named = true,
  },
  [sym__field] = {
    .visible = false,
    .named = true,
  },
  [sym_message_field] = {
    .visible = true,
    .named = true,
  },
  [sym_message_list] = {
    .visible = true,
    .named = true,
  },
  [sym_message_value] = {
    .visible = true,
    .named = true,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_extension_name] = {
    .visible = true,
    .named = true,
  },
  [sym_any_name] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_domain] = {
    .visible = true,
    .named = true,
  },
  [sym__scalar_value] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_signed_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_dec_signed_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_oct_signed_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_signed_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_dec_unsigned_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_oct_unsigned_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_unsigned_integer] = {
    .visible = true,
    .named = true,
  },
  [sym__string] = {
    .visible = false,
    .named = true,
  },
  [sym__float] = {
    .visible = false,
    .named = true,
  },
  [sym__dec_int] = {
    .visible = false,
    .named = true,
  },
  [sym_float_lit] = {
    .visible = true,
    .named = true,
  },
  [sym__exp] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__dec_lit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__oct_int_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__hex_int_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scalar_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == 11) ADVANCE(19);
      if (lookahead == '\f') ADVANCE(20);
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '+') ADVANCE(47);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '.') ADVANCE(41);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '0') ADVANCE(14);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '<') ADVANCE(38);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == 'E') ADVANCE(45);
      if (lookahead == 'F') ADVANCE(43);
      if (lookahead == 'X') ADVANCE(17);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == 'e') ADVANCE(46);
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == 'x') ADVANCE(18);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '7')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'D') ||
          ('a' <= lookahead && lookahead <= 'd')) ADVANCE(11);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2)
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 4:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '.') ADVANCE(41);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '0') ADVANCE(14);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '<') ADVANCE(38);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 5:
      if (eof) ADVANCE(10);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '+') ADVANCE(47);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == 'E') ADVANCE(45);
      if (lookahead == 'F') ADVANCE(43);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == 'e') ADVANCE(46);
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 6:
      if (eof) ADVANCE(10);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == 'F') ADVANCE(43);
      if (lookahead == 'X') ADVANCE(17);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == 'x') ADVANCE(18);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 7:
      if (eof) ADVANCE(10);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == 'F') ADVANCE(43);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__letter);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__oct);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__dec);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym__dec_lit_token1);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__hex);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_X);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_x);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_2);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__ident_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__single_string_token1);
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym__single_string_token1);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym__single_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym__double_string_token1);
      if (lookahead == '"') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__double_string_token1);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__double_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_F);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_f);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 9},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 7},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 7},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 4},
  [72] = {.lex_state = 9},
  [73] = {.lex_state = 9},
  [74] = {.lex_state = 8},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 4},
  [80] = {.lex_state = 4},
  [81] = {.lex_state = 4},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 4},
  [84] = {.lex_state = 4},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 4},
  [87] = {.lex_state = 4},
  [88] = {.lex_state = 4},
  [89] = {.lex_state = 5},
  [90] = {.lex_state = 4},
  [91] = {.lex_state = 4},
  [92] = {.lex_state = 4},
  [93] = {.lex_state = 4},
  [94] = {.lex_state = 4},
  [95] = {.lex_state = 4},
  [96] = {.lex_state = 4},
  [97] = {.lex_state = 4},
  [98] = {.lex_state = 4},
  [99] = {.lex_state = 4},
  [100] = {.lex_state = 4},
  [101] = {.lex_state = 4},
  [102] = {.lex_state = 4},
  [103] = {.lex_state = 4},
  [104] = {.lex_state = 4},
  [105] = {.lex_state = 4},
  [106] = {.lex_state = 4},
  [107] = {.lex_state = 4},
  [108] = {.lex_state = 4},
  [109] = {.lex_state = 4},
  [110] = {.lex_state = 4},
  [111] = {.lex_state = 4},
  [112] = {.lex_state = 4},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 4},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 5},
  [119] = {.lex_state = 5},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 4},
  [122] = {.lex_state = 4},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 3},
  [126] = {.lex_state = 3},
  [127] = {.lex_state = 4},
  [128] = {.lex_state = 5},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 4},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 4},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 4},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 4},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 5},
  [149] = {.lex_state = 3},
  [150] = {.lex_state = 4},
  [151] = {.lex_state = 5},
  [152] = {.lex_state = 5},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 3},
  [155] = {.lex_state = 3},
  [156] = {.lex_state = 5},
  [157] = {.lex_state = 5},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 5},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 0},
  [162] = {.lex_state = 0},
  [163] = {.lex_state = 21},
  [164] = {.lex_state = 1},
  [165] = {.lex_state = 0},
  [166] = {.lex_state = 0},
  [167] = {.lex_state = 21},
  [168] = {.lex_state = 2},
  [169] = {.lex_state = 2},
  [170] = {.lex_state = 1},
  [171] = {.lex_state = 0},
  [172] = {.lex_state = 0},
  [173] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__letter] = ACTIONS(1),
    [sym__oct] = ACTIONS(1),
    [sym__dec] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [aux_sym__dec_lit_token1] = ACTIONS(1),
    [sym__hex] = ACTIONS(1),
    [anon_sym_X] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [anon_sym_2] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_F] = ACTIONS(1),
    [anon_sym_f] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(171),
    [sym__ident] = STATE(116),
    [sym_scalar_field] = STATE(16),
    [sym__field] = STATE(16),
    [sym_message_field] = STATE(16),
    [sym_field_name] = STATE(77),
    [sym_extension_name] = STATE(116),
    [sym_any_name] = STATE(116),
    [aux_sym_source_file_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__letter] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 21,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__letter,
    ACTIONS(13), 1,
      anon_sym_0,
    ACTIONS(15), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      anon_sym_DASH,
    STATE(57), 1,
      sym__dec_lit,
    STATE(65), 1,
      sym_float_lit,
    STATE(93), 1,
      sym__ident,
    STATE(94), 1,
      sym__dec_int,
    STATE(97), 1,
      sym__hex_int,
    STATE(98), 1,
      sym__float,
    STATE(107), 1,
      sym__oct_int,
    STATE(102), 2,
      sym_message_list,
      sym_message_value,
    STATE(27), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    STATE(91), 12,
      sym_identifier,
      sym_scalar_list,
      sym__scalar_value,
      sym_string,
      sym_float,
      sym_signed_identifier,
      sym_dec_signed_integer,
      sym_oct_signed_integer,
      sym_hex_signed_integer,
      sym_dec_unsigned_integer,
      sym_oct_unsigned_integer,
      sym_hex_unsigned_integer,
  [79] = 21,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(31), 1,
      anon_sym_0,
    ACTIONS(33), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_DOT,
    ACTIONS(47), 1,
      anon_sym_DASH,
    STATE(38), 1,
      sym__dec_lit,
    STATE(46), 1,
      sym_float_lit,
    STATE(53), 1,
      sym__ident,
    STATE(54), 1,
      sym__oct_int,
    STATE(60), 1,
      sym__dec_int,
    STATE(61), 1,
      sym__float,
    STATE(63), 1,
      sym__hex_int,
    STATE(76), 2,
      sym_message_list,
      sym_message_value,
    STATE(8), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    STATE(83), 12,
      sym_identifier,
      sym_scalar_list,
      sym__scalar_value,
      sym_string,
      sym_float,
      sym_signed_identifier,
      sym_dec_signed_integer,
      sym_oct_signed_integer,
      sym_hex_signed_integer,
      sym_dec_unsigned_integer,
      sym_oct_unsigned_integer,
      sym_hex_unsigned_integer,
  [158] = 21,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(49), 1,
      anon_sym_0,
    ACTIONS(51), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym_DASH,
    STATE(38), 1,
      sym__dec_lit,
    STATE(46), 1,
      sym_float_lit,
    STATE(53), 1,
      sym__ident,
    STATE(54), 1,
      sym__oct_int,
    STATE(60), 1,
      sym__dec_int,
    STATE(61), 1,
      sym__float,
    STATE(63), 1,
      sym__hex_int,
    STATE(143), 1,
      sym_message_value,
    STATE(8), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    STATE(138), 11,
      sym_identifier,
      sym__scalar_value,
      sym_string,
      sym_float,
      sym_signed_identifier,
      sym_dec_signed_integer,
      sym_oct_signed_integer,
      sym_hex_signed_integer,
      sym_dec_unsigned_integer,
      sym_oct_unsigned_integer,
      sym_hex_unsigned_integer,
  [235] = 21,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(49), 1,
      anon_sym_0,
    ACTIONS(51), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym_DASH,
    ACTIONS(59), 1,
      anon_sym_RBRACK,
    STATE(38), 1,
      sym__dec_lit,
    STATE(46), 1,
      sym_float_lit,
    STATE(53), 1,
      sym__ident,
    STATE(54), 1,
      sym__oct_int,
    STATE(60), 1,
      sym__dec_int,
    STATE(61), 1,
      sym__float,
    STATE(63), 1,
      sym__hex_int,
    STATE(130), 1,
      sym_message_value,
    STATE(8), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    STATE(135), 11,
      sym_identifier,
      sym__scalar_value,
      sym_string,
      sym_float,
      sym_signed_identifier,
      sym_dec_signed_integer,
      sym_oct_signed_integer,
      sym_hex_signed_integer,
      sym_dec_unsigned_integer,
      sym_oct_unsigned_integer,
      sym_hex_unsigned_integer,
  [312] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(49), 1,
      anon_sym_0,
    ACTIONS(51), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym_DASH,
    STATE(38), 1,
      sym__dec_lit,
    STATE(46), 1,
      sym_float_lit,
    STATE(53), 1,
      sym__ident,
    STATE(54), 1,
      sym__oct_int,
    STATE(60), 1,
      sym__dec_int,
    STATE(61), 1,
      sym__float,
    STATE(63), 1,
      sym__hex_int,
    STATE(8), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    STATE(158), 11,
      sym_identifier,
      sym__scalar_value,
      sym_string,
      sym_float,
      sym_signed_identifier,
      sym_dec_signed_integer,
      sym_oct_signed_integer,
      sym_hex_signed_integer,
      sym_dec_unsigned_integer,
      sym_oct_unsigned_integer,
      sym_hex_unsigned_integer,
  [377] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym__letter,
    ACTIONS(63), 1,
      sym__dec,
    STATE(10), 1,
      aux_sym__dec_lit_repeat1,
    STATE(42), 1,
      sym__exp,
    ACTIONS(67), 2,
      anon_sym_E,
      anon_sym_e,
    ACTIONS(65), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [406] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    STATE(9), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    ACTIONS(69), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [431] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_SQUOTE,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(9), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    ACTIONS(71), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [456] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym__letter,
    ACTIONS(81), 1,
      sym__dec,
    STATE(10), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(84), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
      anon_sym_E,
      anon_sym_e,
  [481] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym__letter,
    ACTIONS(88), 1,
      sym__oct,
    STATE(47), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(90), 2,
      anon_sym_X,
      anon_sym_x,
    ACTIONS(92), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [507] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym__letter,
    ACTIONS(94), 1,
      sym__dec,
    STATE(25), 1,
      aux_sym__dec_lit_repeat1,
    STATE(70), 1,
      sym__exp,
    ACTIONS(96), 2,
      anon_sym_E,
      anon_sym_e,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [535] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      sym__letter,
    ACTIONS(101), 1,
      anon_sym_LBRACK,
    STATE(82), 1,
      sym_field_name,
    ACTIONS(104), 2,
      anon_sym_RBRACE,
      anon_sym_GT,
    STATE(116), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(13), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [563] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 12,
      sym__letter,
      anon_sym_COLON,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_DOT,
  [581] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(31), 1,
      anon_sym_0,
    ACTIONS(33), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(45), 1,
      anon_sym_DOT,
    STATE(38), 1,
      sym__dec_lit,
    STATE(46), 1,
      sym_float_lit,
    STATE(55), 1,
      sym__oct_int,
    STATE(62), 1,
      sym__float,
    STATE(64), 1,
      sym__dec_int,
    STATE(66), 1,
      sym__ident,
    STATE(71), 1,
      sym__hex_int,
  [618] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    STATE(77), 1,
      sym_field_name,
    STATE(116), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(17), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [645] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      sym__letter,
    ACTIONS(101), 1,
      anon_sym_LBRACK,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    STATE(77), 1,
      sym_field_name,
    STATE(116), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(17), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [672] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(110), 1,
      anon_sym_GT,
    STATE(82), 1,
      sym_field_name,
    STATE(116), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(26), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [699] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_field_name,
    STATE(116), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(24), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [726] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_field_name,
    STATE(116), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(13), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [753] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_SQUOTE,
    ACTIONS(117), 1,
      anon_sym_DQUOTE,
    STATE(21), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    ACTIONS(71), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [776] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym__letter,
    ACTIONS(120), 1,
      sym__oct,
    STATE(67), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(122), 2,
      anon_sym_X,
      anon_sym_x,
    ACTIONS(92), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [801] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_field_name,
    STATE(116), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(20), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [828] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_field_name,
    STATE(116), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(13), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [855] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym__letter,
    ACTIONS(128), 1,
      sym__dec,
    STATE(25), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(84), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
      anon_sym_E,
      anon_sym_e,
  [878] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(126), 1,
      anon_sym_GT,
    STATE(82), 1,
      sym_field_name,
    STATE(116), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(13), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [905] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(21), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    ACTIONS(69), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [928] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__letter,
    ACTIONS(13), 1,
      anon_sym_0,
    ACTIONS(15), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(27), 1,
      anon_sym_DOT,
    STATE(57), 1,
      sym__dec_lit,
    STATE(65), 1,
      sym_float_lit,
    STATE(101), 1,
      sym__dec_int,
    STATE(104), 1,
      sym__float,
    STATE(105), 1,
      sym__ident,
    STATE(106), 1,
      sym__hex_int,
    STATE(109), 1,
      sym__oct_int,
  [965] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(112), 1,
      anon_sym_GT,
    STATE(82), 1,
      sym_field_name,
    STATE(116), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(13), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [992] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(49), 1,
      anon_sym_0,
    ACTIONS(51), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(55), 1,
      anon_sym_DOT,
    STATE(38), 1,
      sym__dec_lit,
    STATE(46), 1,
      sym_float_lit,
    STATE(55), 1,
      sym__oct_int,
    STATE(62), 1,
      sym__float,
    STATE(64), 1,
      sym__dec_int,
    STATE(66), 1,
      sym__ident,
    STATE(71), 1,
      sym__hex_int,
  [1029] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(124), 1,
      anon_sym_GT,
    STATE(82), 1,
      sym_field_name,
    STATE(116), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(29), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [1056] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym__letter,
    ACTIONS(131), 1,
      sym__dec,
    STATE(33), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(92), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [1078] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym__letter,
    ACTIONS(135), 1,
      sym__dec,
    STATE(34), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(137), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [1100] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym__letter,
    ACTIONS(139), 1,
      sym__dec,
    STATE(34), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(84), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [1122] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym__dec,
    ACTIONS(142), 1,
      sym__letter,
    STATE(34), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(144), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [1144] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym__dec,
    ACTIONS(146), 1,
      sym__letter,
    STATE(34), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(148), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [1166] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 9,
      sym__letter,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1181] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym__letter,
    ACTIONS(156), 2,
      anon_sym_F,
      anon_sym_f,
    ACTIONS(154), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1200] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym__letter,
    ACTIONS(158), 1,
      sym__dec,
    STATE(49), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(92), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [1221] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      sym__letter,
    ACTIONS(160), 1,
      sym__dec,
    STATE(43), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(144), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [1242] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      sym__letter,
    ACTIONS(160), 1,
      sym__dec,
    STATE(43), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(148), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [1263] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym__letter,
    ACTIONS(164), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [1280] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym__letter,
    ACTIONS(166), 1,
      sym__dec,
    STATE(43), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(84), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [1301] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 9,
      sym__letter,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1316] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym__oct,
    STATE(45), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(171), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1335] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym__letter,
    ACTIONS(156), 2,
      anon_sym_F,
      anon_sym_f,
    ACTIONS(178), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1354] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      sym__oct,
    STATE(45), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(180), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1373] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym__dec,
    STATE(10), 1,
      aux_sym__dec_lit_repeat1,
    STATE(42), 1,
      sym__exp,
    ACTIONS(184), 2,
      anon_sym_E,
      anon_sym_e,
    ACTIONS(65), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_F,
      anon_sym_f,
  [1396] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym__letter,
    ACTIONS(160), 1,
      sym__dec,
    STATE(43), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(137), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [1417] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym__oct,
    STATE(47), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(186), 2,
      anon_sym_X,
      anon_sym_x,
    ACTIONS(92), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_F,
      anon_sym_f,
  [1437] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      sym__hex,
    STATE(51), 1,
      aux_sym__hex_int_repeat1,
    ACTIONS(188), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1455] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      sym__hex,
    STATE(51), 1,
      aux_sym__hex_int_repeat1,
    ACTIONS(193), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1473] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1486] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1499] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1512] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1525] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      sym__letter,
    ACTIONS(205), 2,
      anon_sym_F,
      anon_sym_f,
    ACTIONS(154), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1542] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1555] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1568] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1581] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1594] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1607] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1620] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1633] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym__letter,
    ACTIONS(205), 2,
      anon_sym_F,
      anon_sym_f,
    ACTIONS(178), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1650] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1663] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym__oct,
    STATE(74), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(180), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1680] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 7,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1693] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 7,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1706] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym__letter,
    ACTIONS(164), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [1721] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1734] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym__hex,
    STATE(72), 1,
      aux_sym__hex_int_repeat1,
    ACTIONS(188), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1751] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym__hex,
    STATE(72), 1,
      aux_sym__hex_int_repeat1,
    ACTIONS(193), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1768] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym__oct,
    STATE(74), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(171), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1785] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym__dec,
    STATE(10), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(148), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_F,
      anon_sym_f,
  [1801] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(235), 4,
      sym__letter,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1815] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(239), 1,
      anon_sym_COLON,
    ACTIONS(241), 1,
      anon_sym_LBRACK,
    STATE(110), 2,
      sym_message_list,
      sym_message_value,
  [1835] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym__dec,
    STATE(10), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(137), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_F,
      anon_sym_f,
  [1851] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1863] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1875] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1887] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(249), 1,
      anon_sym_COLON,
    ACTIONS(251), 1,
      anon_sym_LBRACK,
    STATE(87), 2,
      sym_message_list,
      sym_message_value,
  [1907] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(253), 4,
      sym__letter,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1921] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1933] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym__dec,
    STATE(78), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(92), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_F,
      anon_sym_f,
  [1949] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1961] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(263), 4,
      sym__letter,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1975] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1987] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym__dec,
    STATE(10), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(144), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_F,
      anon_sym_f,
  [2003] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2014] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(253), 3,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_LBRACK,
  [2027] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2038] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2049] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2060] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2071] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2082] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2093] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2104] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2115] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2126] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2137] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(235), 3,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_LBRACK,
  [2150] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2161] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2183] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2194] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2205] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2227] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(263), 3,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_LBRACK,
  [2240] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2251] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2262] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 4,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT,
  [2272] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_RBRACK,
    ACTIONS(279), 1,
      anon_sym_SLASH,
    ACTIONS(281), 1,
      anon_sym_DOT,
    STATE(120), 1,
      aux_sym_type_name_repeat1,
  [2288] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    STATE(129), 1,
      sym__ident,
    STATE(161), 1,
      sym_domain,
    STATE(162), 1,
      sym_type_name,
  [2304] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 4,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT,
  [2314] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(285), 1,
      anon_sym_RBRACK,
    STATE(143), 1,
      sym_message_value,
  [2330] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym__dec,
    STATE(35), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(289), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [2344] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      sym__dec,
    STATE(40), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(293), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [2358] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_DOT,
    STATE(120), 1,
      aux_sym_type_name_repeat1,
    ACTIONS(295), 2,
      anon_sym_RBRACK,
      anon_sym_SLASH,
  [2372] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 4,
      sym__letter,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [2382] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 4,
      sym__letter,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [2392] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 4,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT,
  [2402] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(306), 1,
      anon_sym_RBRACK,
    STATE(130), 1,
      sym_message_value,
  [2418] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      sym__hex,
    STATE(125), 1,
      aux_sym__hex_int_repeat1,
    ACTIONS(188), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2432] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      sym__hex,
    STATE(125), 1,
      aux_sym__hex_int_repeat1,
    ACTIONS(193), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2446] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 4,
      sym__letter,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [2456] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      sym__dec,
    STATE(89), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(315), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [2470] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_DOT,
    ACTIONS(317), 1,
      anon_sym_RBRACK,
    ACTIONS(319), 1,
      anon_sym_SLASH,
    STATE(114), 1,
      aux_sym_type_name_repeat1,
  [2486] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_COMMA,
    ACTIONS(323), 1,
      anon_sym_RBRACK,
    STATE(141), 1,
      aux_sym_message_list_repeat1,
  [2499] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 3,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_LBRACK,
  [2508] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_RBRACK,
    ACTIONS(281), 1,
      anon_sym_DOT,
    STATE(120), 1,
      aux_sym_type_name_repeat1,
  [2521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 3,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_LBRACK,
  [2530] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    STATE(153), 1,
      sym_message_value,
  [2543] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_COMMA,
    ACTIONS(327), 1,
      anon_sym_RBRACK,
    STATE(147), 1,
      aux_sym_scalar_list_repeat1,
  [2556] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_COMMA,
    ACTIONS(329), 1,
      anon_sym_RBRACK,
    STATE(139), 1,
      aux_sym_scalar_list_repeat1,
  [2569] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_COMMA,
    ACTIONS(331), 1,
      anon_sym_RBRACK,
    STATE(142), 1,
      aux_sym_message_list_repeat1,
  [2582] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_COMMA,
    ACTIONS(333), 1,
      anon_sym_RBRACK,
    STATE(136), 1,
      aux_sym_scalar_list_repeat1,
  [2595] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_COMMA,
    ACTIONS(338), 1,
      anon_sym_RBRACK,
    STATE(139), 1,
      aux_sym_scalar_list_repeat1,
  [2608] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 3,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_LBRACK,
  [2617] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_COMMA,
    ACTIONS(340), 1,
      anon_sym_RBRACK,
    STATE(142), 1,
      aux_sym_message_list_repeat1,
  [2630] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(342), 1,
      anon_sym_COMMA,
    ACTIONS(345), 1,
      anon_sym_RBRACK,
    STATE(142), 1,
      aux_sym_message_list_repeat1,
  [2643] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_COMMA,
    ACTIONS(347), 1,
      anon_sym_RBRACK,
    STATE(137), 1,
      aux_sym_message_list_repeat1,
  [2656] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 3,
      anon_sym_RBRACK,
      anon_sym_SLASH,
      anon_sym_DOT,
  [2665] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    STATE(146), 1,
      sym__ident,
    STATE(166), 1,
      sym_type_name,
  [2678] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_DOT,
    ACTIONS(317), 1,
      anon_sym_RBRACK,
    STATE(132), 1,
      aux_sym_type_name_repeat1,
  [2691] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_COMMA,
    ACTIONS(349), 1,
      anon_sym_RBRACK,
    STATE(139), 1,
      aux_sym_scalar_list_repeat1,
  [2704] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      sym__dec,
    STATE(12), 1,
      aux_sym__dec_lit_repeat1,
  [2714] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      sym__hex,
    STATE(73), 1,
      aux_sym__hex_int_repeat1,
  [2724] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    STATE(144), 1,
      sym__ident,
  [2734] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      sym__dec,
    STATE(48), 1,
      aux_sym__dec_lit_repeat1,
  [2744] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      sym__dec,
    STATE(7), 1,
      aux_sym__dec_lit_repeat1,
  [2754] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2762] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      sym__hex,
    STATE(52), 1,
      aux_sym__hex_int_repeat1,
  [2772] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      sym__hex,
    STATE(126), 1,
      aux_sym__hex_int_repeat1,
  [2782] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      sym__dec,
    STATE(36), 1,
      aux_sym__dec_lit_repeat1,
  [2792] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      sym__dec,
    STATE(75), 1,
      aux_sym__dec_lit_repeat1,
  [2802] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2810] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      sym__dec,
    STATE(41), 1,
      aux_sym__dec_lit_repeat1,
  [2820] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      anon_sym_DQUOTE,
  [2827] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      anon_sym_SLASH,
  [2834] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      anon_sym_RBRACK,
  [2841] = 2,
    ACTIONS(375), 1,
      aux_sym__ident_token1,
    ACTIONS(377), 1,
      sym_comment,
  [2848] = 2,
    ACTIONS(377), 1,
      sym_comment,
    ACTIONS(379), 1,
      aux_sym__double_string_token1,
  [2855] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 1,
      anon_sym_SQUOTE,
  [2862] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(383), 1,
      anon_sym_RBRACK,
  [2869] = 2,
    ACTIONS(377), 1,
      sym_comment,
    ACTIONS(385), 1,
      aux_sym__ident_token1,
  [2876] = 2,
    ACTIONS(377), 1,
      sym_comment,
    ACTIONS(387), 1,
      aux_sym__single_string_token1,
  [2883] = 2,
    ACTIONS(377), 1,
      sym_comment,
    ACTIONS(389), 1,
      aux_sym__single_string_token1,
  [2890] = 2,
    ACTIONS(377), 1,
      sym_comment,
    ACTIONS(391), 1,
      aux_sym__double_string_token1,
  [2897] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(393), 1,
      ts_builtin_sym_end,
  [2904] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 1,
      anon_sym_SQUOTE,
  [2911] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(397), 1,
      anon_sym_DQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 79,
  [SMALL_STATE(4)] = 158,
  [SMALL_STATE(5)] = 235,
  [SMALL_STATE(6)] = 312,
  [SMALL_STATE(7)] = 377,
  [SMALL_STATE(8)] = 406,
  [SMALL_STATE(9)] = 431,
  [SMALL_STATE(10)] = 456,
  [SMALL_STATE(11)] = 481,
  [SMALL_STATE(12)] = 507,
  [SMALL_STATE(13)] = 535,
  [SMALL_STATE(14)] = 563,
  [SMALL_STATE(15)] = 581,
  [SMALL_STATE(16)] = 618,
  [SMALL_STATE(17)] = 645,
  [SMALL_STATE(18)] = 672,
  [SMALL_STATE(19)] = 699,
  [SMALL_STATE(20)] = 726,
  [SMALL_STATE(21)] = 753,
  [SMALL_STATE(22)] = 776,
  [SMALL_STATE(23)] = 801,
  [SMALL_STATE(24)] = 828,
  [SMALL_STATE(25)] = 855,
  [SMALL_STATE(26)] = 878,
  [SMALL_STATE(27)] = 905,
  [SMALL_STATE(28)] = 928,
  [SMALL_STATE(29)] = 965,
  [SMALL_STATE(30)] = 992,
  [SMALL_STATE(31)] = 1029,
  [SMALL_STATE(32)] = 1056,
  [SMALL_STATE(33)] = 1078,
  [SMALL_STATE(34)] = 1100,
  [SMALL_STATE(35)] = 1122,
  [SMALL_STATE(36)] = 1144,
  [SMALL_STATE(37)] = 1166,
  [SMALL_STATE(38)] = 1181,
  [SMALL_STATE(39)] = 1200,
  [SMALL_STATE(40)] = 1221,
  [SMALL_STATE(41)] = 1242,
  [SMALL_STATE(42)] = 1263,
  [SMALL_STATE(43)] = 1280,
  [SMALL_STATE(44)] = 1301,
  [SMALL_STATE(45)] = 1316,
  [SMALL_STATE(46)] = 1335,
  [SMALL_STATE(47)] = 1354,
  [SMALL_STATE(48)] = 1373,
  [SMALL_STATE(49)] = 1396,
  [SMALL_STATE(50)] = 1417,
  [SMALL_STATE(51)] = 1437,
  [SMALL_STATE(52)] = 1455,
  [SMALL_STATE(53)] = 1473,
  [SMALL_STATE(54)] = 1486,
  [SMALL_STATE(55)] = 1499,
  [SMALL_STATE(56)] = 1512,
  [SMALL_STATE(57)] = 1525,
  [SMALL_STATE(58)] = 1542,
  [SMALL_STATE(59)] = 1555,
  [SMALL_STATE(60)] = 1568,
  [SMALL_STATE(61)] = 1581,
  [SMALL_STATE(62)] = 1594,
  [SMALL_STATE(63)] = 1607,
  [SMALL_STATE(64)] = 1620,
  [SMALL_STATE(65)] = 1633,
  [SMALL_STATE(66)] = 1650,
  [SMALL_STATE(67)] = 1663,
  [SMALL_STATE(68)] = 1680,
  [SMALL_STATE(69)] = 1693,
  [SMALL_STATE(70)] = 1706,
  [SMALL_STATE(71)] = 1721,
  [SMALL_STATE(72)] = 1734,
  [SMALL_STATE(73)] = 1751,
  [SMALL_STATE(74)] = 1768,
  [SMALL_STATE(75)] = 1785,
  [SMALL_STATE(76)] = 1801,
  [SMALL_STATE(77)] = 1815,
  [SMALL_STATE(78)] = 1835,
  [SMALL_STATE(79)] = 1851,
  [SMALL_STATE(80)] = 1863,
  [SMALL_STATE(81)] = 1875,
  [SMALL_STATE(82)] = 1887,
  [SMALL_STATE(83)] = 1907,
  [SMALL_STATE(84)] = 1921,
  [SMALL_STATE(85)] = 1933,
  [SMALL_STATE(86)] = 1949,
  [SMALL_STATE(87)] = 1961,
  [SMALL_STATE(88)] = 1975,
  [SMALL_STATE(89)] = 1987,
  [SMALL_STATE(90)] = 2003,
  [SMALL_STATE(91)] = 2014,
  [SMALL_STATE(92)] = 2027,
  [SMALL_STATE(93)] = 2038,
  [SMALL_STATE(94)] = 2049,
  [SMALL_STATE(95)] = 2060,
  [SMALL_STATE(96)] = 2071,
  [SMALL_STATE(97)] = 2082,
  [SMALL_STATE(98)] = 2093,
  [SMALL_STATE(99)] = 2104,
  [SMALL_STATE(100)] = 2115,
  [SMALL_STATE(101)] = 2126,
  [SMALL_STATE(102)] = 2137,
  [SMALL_STATE(103)] = 2150,
  [SMALL_STATE(104)] = 2161,
  [SMALL_STATE(105)] = 2172,
  [SMALL_STATE(106)] = 2183,
  [SMALL_STATE(107)] = 2194,
  [SMALL_STATE(108)] = 2205,
  [SMALL_STATE(109)] = 2216,
  [SMALL_STATE(110)] = 2227,
  [SMALL_STATE(111)] = 2240,
  [SMALL_STATE(112)] = 2251,
  [SMALL_STATE(113)] = 2262,
  [SMALL_STATE(114)] = 2272,
  [SMALL_STATE(115)] = 2288,
  [SMALL_STATE(116)] = 2304,
  [SMALL_STATE(117)] = 2314,
  [SMALL_STATE(118)] = 2330,
  [SMALL_STATE(119)] = 2344,
  [SMALL_STATE(120)] = 2358,
  [SMALL_STATE(121)] = 2372,
  [SMALL_STATE(122)] = 2382,
  [SMALL_STATE(123)] = 2392,
  [SMALL_STATE(124)] = 2402,
  [SMALL_STATE(125)] = 2418,
  [SMALL_STATE(126)] = 2432,
  [SMALL_STATE(127)] = 2446,
  [SMALL_STATE(128)] = 2456,
  [SMALL_STATE(129)] = 2470,
  [SMALL_STATE(130)] = 2486,
  [SMALL_STATE(131)] = 2499,
  [SMALL_STATE(132)] = 2508,
  [SMALL_STATE(133)] = 2521,
  [SMALL_STATE(134)] = 2530,
  [SMALL_STATE(135)] = 2543,
  [SMALL_STATE(136)] = 2556,
  [SMALL_STATE(137)] = 2569,
  [SMALL_STATE(138)] = 2582,
  [SMALL_STATE(139)] = 2595,
  [SMALL_STATE(140)] = 2608,
  [SMALL_STATE(141)] = 2617,
  [SMALL_STATE(142)] = 2630,
  [SMALL_STATE(143)] = 2643,
  [SMALL_STATE(144)] = 2656,
  [SMALL_STATE(145)] = 2665,
  [SMALL_STATE(146)] = 2678,
  [SMALL_STATE(147)] = 2691,
  [SMALL_STATE(148)] = 2704,
  [SMALL_STATE(149)] = 2714,
  [SMALL_STATE(150)] = 2724,
  [SMALL_STATE(151)] = 2734,
  [SMALL_STATE(152)] = 2744,
  [SMALL_STATE(153)] = 2754,
  [SMALL_STATE(154)] = 2762,
  [SMALL_STATE(155)] = 2772,
  [SMALL_STATE(156)] = 2782,
  [SMALL_STATE(157)] = 2792,
  [SMALL_STATE(158)] = 2802,
  [SMALL_STATE(159)] = 2810,
  [SMALL_STATE(160)] = 2820,
  [SMALL_STATE(161)] = 2827,
  [SMALL_STATE(162)] = 2834,
  [SMALL_STATE(163)] = 2841,
  [SMALL_STATE(164)] = 2848,
  [SMALL_STATE(165)] = 2855,
  [SMALL_STATE(166)] = 2862,
  [SMALL_STATE(167)] = 2869,
  [SMALL_STATE(168)] = 2876,
  [SMALL_STATE(169)] = 2883,
  [SMALL_STATE(170)] = 2890,
  [SMALL_STATE(171)] = 2897,
  [SMALL_STATE(172)] = 2904,
  [SMALL_STATE(173)] = 2911,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(163),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(167),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(168),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(164),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(169),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(170),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(151),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float_lit, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_lit, 2),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(169),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(170),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__dec_lit_repeat1, 2),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__dec_lit_repeat1, 2), SHIFT_REPEAT(10),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__dec_lit_repeat1, 2),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dec_lit, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dec_lit, 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(163),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(115),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ident, 2),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(168),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(164),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__dec_lit_repeat1, 2), SHIFT_REPEAT(25),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dec_lit, 2),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dec_lit, 2),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__dec_lit_repeat1, 2), SHIFT_REPEAT(34),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exp, 2),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 2),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exp, 3),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__single_string, 3),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dec_int, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dec_int, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float_lit, 3),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_lit, 3),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__dec_lit_repeat1, 2), SHIFT_REPEAT(43),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__double_string, 3),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__oct_int_repeat1, 2),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__oct_int_repeat1, 2), SHIFT_REPEAT(45),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__float, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__oct_int, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__hex_int_repeat1, 2),
  [190] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__hex_int_repeat1, 2), SHIFT_REPEAT(51),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex_int, 3),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_oct_unsigned_integer, 1),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_oct_signed_integer, 2),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 2),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_value, 2),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_value, 3),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dec_unsigned_integer, 1),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 2),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hex_unsigned_integer, 1),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dec_signed_integer, 2),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signed_identifier, 2),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hex_signed_integer, 2),
  [227] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__hex_int_repeat1, 2), SHIFT_REPEAT(72),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__oct_int_repeat1, 2), SHIFT_REPEAT(74),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 3),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 3),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 2),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_list, 2),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_field, 3),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_list, 3),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 4),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 2),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_list, 4),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension_name, 3),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 2),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 2),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_name, 1),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(156),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 2),
  [297] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 2), SHIFT_REPEAT(150),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_field, 4),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 4),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_any_name, 5),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [308] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__hex_int_repeat1, 2), SHIFT_REPEAT(125),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(157),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 1),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [335] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scalar_list_repeat1, 2), SHIFT_REPEAT(6),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scalar_list_repeat1, 2),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [342] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_list_repeat1, 2), SHIFT_REPEAT(134),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_list_repeat1, 2),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [377] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [379] = {.entry = {.count = 1, .reusable = false}}, SHIFT(173),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [387] = {.entry = {.count = 1, .reusable = false}}, SHIFT(172),
  [389] = {.entry = {.count = 1, .reusable = false}}, SHIFT(165),
  [391] = {.entry = {.count = 1, .reusable = false}}, SHIFT(160),
  [393] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_textproto(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
