#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 176
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 76
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  sym__letter = 1,
  sym__oct = 2,
  sym__dec = 3,
  anon_sym_0 = 4,
  aux_sym__dec_lit_token1 = 5,
  sym__hex = 6,
  anon_sym_X = 7,
  anon_sym_x = 8,
  anon_sym_ = 9,
  anon_sym_2 = 10,
  aux_sym__ident_token1 = 11,
  anon_sym_SQUOTE = 12,
  aux_sym__single_string_token1 = 13,
  anon_sym_DQUOTE = 14,
  aux_sym__double_string_token1 = 15,
  anon_sym_COLON = 16,
  anon_sym_SEMI = 17,
  anon_sym_COMMA = 18,
  anon_sym_LBRACK = 19,
  anon_sym_RBRACK = 20,
  sym_comment = 21,
  anon_sym_LBRACE = 22,
  anon_sym_RBRACE = 23,
  anon_sym_LT = 24,
  anon_sym_GT = 25,
  anon_sym_SLASH = 26,
  anon_sym_DOT = 27,
  anon_sym_DASH = 28,
  anon_sym_F = 29,
  anon_sym_f = 30,
  anon_sym_E = 31,
  anon_sym_e = 32,
  anon_sym_PLUS = 33,
  sym_source_file = 34,
  sym__dec_lit = 35,
  sym__oct_int = 36,
  sym__hex_int = 37,
  sym__ident = 38,
  sym_identifier = 39,
  sym__single_string = 40,
  sym__double_string = 41,
  sym_scalar_field = 42,
  sym_scalar_list = 43,
  sym__field = 44,
  sym_message_field = 45,
  sym_message_list = 46,
  sym_message_value = 47,
  sym_field_name = 48,
  sym_extension_name = 49,
  sym_any_name = 50,
  sym_type_name = 51,
  sym_domain = 52,
  sym_scalar_value = 53,
  sym_string = 54,
  sym_float = 55,
  sym_signed_identifier = 56,
  sym_dec_signed_integer = 57,
  sym_oct_signed_integer = 58,
  sym_hex_signed_integer = 59,
  sym_dec_unsigned_integer = 60,
  sym_oct_unsigned_integer = 61,
  sym_hex_unsigned_integer = 62,
  sym__string = 63,
  sym__float = 64,
  sym__dec_int = 65,
  sym_float_lit = 66,
  sym__exp = 67,
  aux_sym_source_file_repeat1 = 68,
  aux_sym__dec_lit_repeat1 = 69,
  aux_sym__oct_int_repeat1 = 70,
  aux_sym__hex_int_repeat1 = 71,
  aux_sym_scalar_list_repeat1 = 72,
  aux_sym_message_list_repeat1 = 73,
  aux_sym_type_name_repeat1 = 74,
  aux_sym_string_repeat1 = 75,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__letter] = "_letter",
  [sym__oct] = "_oct",
  [sym__dec] = "_dec",
  [anon_sym_0] = "0",
  [aux_sym__dec_lit_token1] = "_dec_lit_token1",
  [sym__hex] = "_hex",
  [anon_sym_X] = "X",
  [anon_sym_x] = "x",
  [anon_sym_] = "",
  [anon_sym_2] = "\f",
  [aux_sym__ident_token1] = "_ident_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__single_string_token1] = "_single_string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__double_string_token1] = "_double_string_token1",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_comment] = "comment",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_SLASH] = "/",
  [anon_sym_DOT] = ".",
  [anon_sym_DASH] = "-",
  [anon_sym_F] = "F",
  [anon_sym_f] = "f",
  [anon_sym_E] = "E",
  [anon_sym_e] = "e",
  [anon_sym_PLUS] = "+",
  [sym_source_file] = "source_file",
  [sym__dec_lit] = "_dec_lit",
  [sym__oct_int] = "_oct_int",
  [sym__hex_int] = "_hex_int",
  [sym__ident] = "_ident",
  [sym_identifier] = "identifier",
  [sym__single_string] = "_single_string",
  [sym__double_string] = "_double_string",
  [sym_scalar_field] = "scalar_field",
  [sym_scalar_list] = "scalar_list",
  [sym__field] = "_field",
  [sym_message_field] = "message_field",
  [sym_message_list] = "message_list",
  [sym_message_value] = "message_value",
  [sym_field_name] = "field_name",
  [sym_extension_name] = "extension_name",
  [sym_any_name] = "any_name",
  [sym_type_name] = "type_name",
  [sym_domain] = "domain",
  [sym_scalar_value] = "scalar_value",
  [sym_string] = "string",
  [sym_float] = "float",
  [sym_signed_identifier] = "signed_identifier",
  [sym_dec_signed_integer] = "dec_signed_integer",
  [sym_oct_signed_integer] = "oct_signed_integer",
  [sym_hex_signed_integer] = "hex_signed_integer",
  [sym_dec_unsigned_integer] = "dec_unsigned_integer",
  [sym_oct_unsigned_integer] = "oct_unsigned_integer",
  [sym_hex_unsigned_integer] = "hex_unsigned_integer",
  [sym__string] = "_string",
  [sym__float] = "_float",
  [sym__dec_int] = "_dec_int",
  [sym_float_lit] = "float_lit",
  [sym__exp] = "_exp",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__dec_lit_repeat1] = "_dec_lit_repeat1",
  [aux_sym__oct_int_repeat1] = "_oct_int_repeat1",
  [aux_sym__hex_int_repeat1] = "_hex_int_repeat1",
  [aux_sym_scalar_list_repeat1] = "scalar_list_repeat1",
  [aux_sym_message_list_repeat1] = "message_list_repeat1",
  [aux_sym_type_name_repeat1] = "type_name_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__letter] = sym__letter,
  [sym__oct] = sym__oct,
  [sym__dec] = sym__dec,
  [anon_sym_0] = anon_sym_0,
  [aux_sym__dec_lit_token1] = aux_sym__dec_lit_token1,
  [sym__hex] = sym__hex,
  [anon_sym_X] = anon_sym_X,
  [anon_sym_x] = anon_sym_x,
  [anon_sym_] = anon_sym_,
  [anon_sym_2] = anon_sym_2,
  [aux_sym__ident_token1] = aux_sym__ident_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__single_string_token1] = aux_sym__single_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__double_string_token1] = aux_sym__double_string_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_F] = anon_sym_F,
  [anon_sym_f] = anon_sym_f,
  [anon_sym_E] = anon_sym_E,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_source_file] = sym_source_file,
  [sym__dec_lit] = sym__dec_lit,
  [sym__oct_int] = sym__oct_int,
  [sym__hex_int] = sym__hex_int,
  [sym__ident] = sym__ident,
  [sym_identifier] = sym_identifier,
  [sym__single_string] = sym__single_string,
  [sym__double_string] = sym__double_string,
  [sym_scalar_field] = sym_scalar_field,
  [sym_scalar_list] = sym_scalar_list,
  [sym__field] = sym__field,
  [sym_message_field] = sym_message_field,
  [sym_message_list] = sym_message_list,
  [sym_message_value] = sym_message_value,
  [sym_field_name] = sym_field_name,
  [sym_extension_name] = sym_extension_name,
  [sym_any_name] = sym_any_name,
  [sym_type_name] = sym_type_name,
  [sym_domain] = sym_domain,
  [sym_scalar_value] = sym_scalar_value,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [sym_signed_identifier] = sym_signed_identifier,
  [sym_dec_signed_integer] = sym_dec_signed_integer,
  [sym_oct_signed_integer] = sym_oct_signed_integer,
  [sym_hex_signed_integer] = sym_hex_signed_integer,
  [sym_dec_unsigned_integer] = sym_dec_unsigned_integer,
  [sym_oct_unsigned_integer] = sym_oct_unsigned_integer,
  [sym_hex_unsigned_integer] = sym_hex_unsigned_integer,
  [sym__string] = sym__string,
  [sym__float] = sym__float,
  [sym__dec_int] = sym__dec_int,
  [sym_float_lit] = sym_float_lit,
  [sym__exp] = sym__exp,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__dec_lit_repeat1] = aux_sym__dec_lit_repeat1,
  [aux_sym__oct_int_repeat1] = aux_sym__oct_int_repeat1,
  [aux_sym__hex_int_repeat1] = aux_sym__hex_int_repeat1,
  [aux_sym_scalar_list_repeat1] = aux_sym_scalar_list_repeat1,
  [aux_sym_message_list_repeat1] = aux_sym_message_list_repeat1,
  [aux_sym_type_name_repeat1] = aux_sym_type_name_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__letter] = {
    .visible = false,
    .named = true,
  },
  [sym__oct] = {
    .visible = false,
    .named = true,
  },
  [sym__dec] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__dec_lit_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__hex] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_X] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__ident_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__single_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__double_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_F] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_E] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__dec_lit] = {
    .visible = false,
    .named = true,
  },
  [sym__oct_int] = {
    .visible = false,
    .named = true,
  },
  [sym__hex_int] = {
    .visible = false,
    .named = true,
  },
  [sym__ident] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__single_string] = {
    .visible = false,
    .named = true,
  },
  [sym__double_string] = {
    .visible = false,
    .named = true,
  },
  [sym_scalar_field] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_list] = {
    .visible = true,
    .named = true,
  },
  [sym__field] = {
    .visible = false,
    .named = true,
  },
  [sym_message_field] = {
    .visible = true,
    .named = true,
  },
  [sym_message_list] = {
    .visible = true,
    .named = true,
  },
  [sym_message_value] = {
    .visible = true,
    .named = true,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_extension_name] = {
    .visible = true,
    .named = true,
  },
  [sym_any_name] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_domain] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_signed_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_dec_signed_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_oct_signed_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_signed_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_dec_unsigned_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_oct_unsigned_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_unsigned_integer] = {
    .visible = true,
    .named = true,
  },
  [sym__string] = {
    .visible = false,
    .named = true,
  },
  [sym__float] = {
    .visible = false,
    .named = true,
  },
  [sym__dec_int] = {
    .visible = false,
    .named = true,
  },
  [sym_float_lit] = {
    .visible = true,
    .named = true,
  },
  [sym__exp] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__dec_lit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__oct_int_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__hex_int_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scalar_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == 11) ADVANCE(19);
      if (lookahead == '\f') ADVANCE(20);
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '+') ADVANCE(47);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '.') ADVANCE(41);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '0') ADVANCE(14);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '<') ADVANCE(38);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == 'E') ADVANCE(45);
      if (lookahead == 'F') ADVANCE(43);
      if (lookahead == 'X') ADVANCE(17);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == 'e') ADVANCE(46);
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == 'x') ADVANCE(18);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '7')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'D') ||
          ('a' <= lookahead && lookahead <= 'd')) ADVANCE(11);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2)
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 4:
      if (eof) ADVANCE(10);
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '.') ADVANCE(41);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '0') ADVANCE(14);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '<') ADVANCE(38);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 5:
      if (eof) ADVANCE(10);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '+') ADVANCE(47);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == 'E') ADVANCE(45);
      if (lookahead == 'F') ADVANCE(43);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == 'e') ADVANCE(46);
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 6:
      if (eof) ADVANCE(10);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == 'F') ADVANCE(43);
      if (lookahead == 'X') ADVANCE(17);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == 'x') ADVANCE(18);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 7:
      if (eof) ADVANCE(10);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == 'F') ADVANCE(43);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == 'f') ADVANCE(44);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__letter);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__oct);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__dec);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym__dec_lit_token1);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__hex);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_X);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_x);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_2);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__ident_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__single_string_token1);
      if (lookahead == '#') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym__single_string_token1);
      if (lookahead == '\'') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym__single_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym__double_string_token1);
      if (lookahead == '"') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__double_string_token1);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__double_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_F);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_f);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_E);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 8},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 9},
  [51] = {.lex_state = 9},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 7},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 7},
  [72] = {.lex_state = 4},
  [73] = {.lex_state = 9},
  [74] = {.lex_state = 9},
  [75] = {.lex_state = 8},
  [76] = {.lex_state = 5},
  [77] = {.lex_state = 4},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 5},
  [80] = {.lex_state = 4},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 4},
  [83] = {.lex_state = 4},
  [84] = {.lex_state = 4},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 4},
  [87] = {.lex_state = 4},
  [88] = {.lex_state = 5},
  [89] = {.lex_state = 4},
  [90] = {.lex_state = 4},
  [91] = {.lex_state = 4},
  [92] = {.lex_state = 4},
  [93] = {.lex_state = 4},
  [94] = {.lex_state = 4},
  [95] = {.lex_state = 4},
  [96] = {.lex_state = 4},
  [97] = {.lex_state = 4},
  [98] = {.lex_state = 4},
  [99] = {.lex_state = 4},
  [100] = {.lex_state = 4},
  [101] = {.lex_state = 4},
  [102] = {.lex_state = 4},
  [103] = {.lex_state = 4},
  [104] = {.lex_state = 4},
  [105] = {.lex_state = 4},
  [106] = {.lex_state = 4},
  [107] = {.lex_state = 4},
  [108] = {.lex_state = 4},
  [109] = {.lex_state = 4},
  [110] = {.lex_state = 4},
  [111] = {.lex_state = 4},
  [112] = {.lex_state = 4},
  [113] = {.lex_state = 4},
  [114] = {.lex_state = 4},
  [115] = {.lex_state = 4},
  [116] = {.lex_state = 3},
  [117] = {.lex_state = 4},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 5},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 4},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 4},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 3},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 5},
  [131] = {.lex_state = 5},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 4},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 4},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 4},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 4},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 5},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 4},
  [153] = {.lex_state = 5},
  [154] = {.lex_state = 5},
  [155] = {.lex_state = 3},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 3},
  [158] = {.lex_state = 3},
  [159] = {.lex_state = 5},
  [160] = {.lex_state = 5},
  [161] = {.lex_state = 5},
  [162] = {.lex_state = 0},
  [163] = {.lex_state = 0},
  [164] = {.lex_state = 0},
  [165] = {.lex_state = 1},
  [166] = {.lex_state = 0},
  [167] = {.lex_state = 2},
  [168] = {.lex_state = 21},
  [169] = {.lex_state = 0},
  [170] = {.lex_state = 0},
  [171] = {.lex_state = 2},
  [172] = {.lex_state = 1},
  [173] = {.lex_state = 0},
  [174] = {.lex_state = 0},
  [175] = {.lex_state = 21},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__letter] = ACTIONS(1),
    [sym__oct] = ACTIONS(1),
    [sym__dec] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [aux_sym__dec_lit_token1] = ACTIONS(1),
    [sym__hex] = ACTIONS(1),
    [anon_sym_X] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [anon_sym_2] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_F] = ACTIONS(1),
    [anon_sym_f] = ACTIONS(1),
    [anon_sym_E] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(173),
    [sym__ident] = STATE(118),
    [sym_scalar_field] = STATE(16),
    [sym__field] = STATE(16),
    [sym_message_field] = STATE(16),
    [sym_field_name] = STATE(78),
    [sym_extension_name] = STATE(118),
    [sym_any_name] = STATE(118),
    [aux_sym_source_file_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__letter] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 22,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__letter,
    ACTIONS(13), 1,
      anon_sym_0,
    ACTIONS(15), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      anon_sym_DASH,
    STATE(53), 1,
      sym__dec_lit,
    STATE(59), 1,
      sym_float_lit,
    STATE(96), 1,
      sym__dec_int,
    STATE(98), 1,
      sym__hex_int,
    STATE(102), 1,
      sym__ident,
    STATE(104), 1,
      sym__float,
    STATE(109), 1,
      sym__oct_int,
    STATE(105), 2,
      sym_message_list,
      sym_message_value,
    STATE(110), 2,
      sym_scalar_list,
      sym_scalar_value,
    STATE(21), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    STATE(94), 10,
      sym_identifier,
      sym_string,
      sym_float,
      sym_signed_identifier,
      sym_dec_signed_integer,
      sym_oct_signed_integer,
      sym_hex_signed_integer,
      sym_dec_unsigned_integer,
      sym_oct_unsigned_integer,
      sym_hex_unsigned_integer,
  [81] = 22,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(31), 1,
      anon_sym_0,
    ACTIONS(33), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_DOT,
    ACTIONS(47), 1,
      anon_sym_DASH,
    STATE(46), 1,
      sym__dec_lit,
    STATE(47), 1,
      sym_float_lit,
    STATE(54), 1,
      sym__hex_int,
    STATE(60), 1,
      sym__dec_int,
    STATE(61), 1,
      sym__float,
    STATE(63), 1,
      sym__ident,
    STATE(65), 1,
      sym__oct_int,
    STATE(83), 2,
      sym_message_list,
      sym_message_value,
    STATE(84), 2,
      sym_scalar_list,
      sym_scalar_value,
    STATE(8), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    STATE(62), 10,
      sym_identifier,
      sym_string,
      sym_float,
      sym_signed_identifier,
      sym_dec_signed_integer,
      sym_oct_signed_integer,
      sym_hex_signed_integer,
      sym_dec_unsigned_integer,
      sym_oct_unsigned_integer,
      sym_hex_unsigned_integer,
  [162] = 22,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(49), 1,
      anon_sym_0,
    ACTIONS(51), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym_DASH,
    STATE(46), 1,
      sym__dec_lit,
    STATE(47), 1,
      sym_float_lit,
    STATE(54), 1,
      sym__hex_int,
    STATE(60), 1,
      sym__dec_int,
    STATE(61), 1,
      sym__float,
    STATE(63), 1,
      sym__ident,
    STATE(65), 1,
      sym__oct_int,
    STATE(142), 1,
      sym_scalar_value,
    STATE(146), 1,
      sym_message_value,
    STATE(8), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    STATE(62), 10,
      sym_identifier,
      sym_string,
      sym_float,
      sym_signed_identifier,
      sym_dec_signed_integer,
      sym_oct_signed_integer,
      sym_hex_signed_integer,
      sym_dec_unsigned_integer,
      sym_oct_unsigned_integer,
      sym_hex_unsigned_integer,
  [241] = 22,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(49), 1,
      anon_sym_0,
    ACTIONS(51), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym_DASH,
    ACTIONS(59), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      sym__dec_lit,
    STATE(47), 1,
      sym_float_lit,
    STATE(54), 1,
      sym__hex_int,
    STATE(60), 1,
      sym__dec_int,
    STATE(61), 1,
      sym__float,
    STATE(63), 1,
      sym__ident,
    STATE(65), 1,
      sym__oct_int,
    STATE(133), 1,
      sym_message_value,
    STATE(149), 1,
      sym_scalar_value,
    STATE(8), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    STATE(62), 10,
      sym_identifier,
      sym_string,
      sym_float,
      sym_signed_identifier,
      sym_dec_signed_integer,
      sym_oct_signed_integer,
      sym_hex_signed_integer,
      sym_dec_unsigned_integer,
      sym_oct_unsigned_integer,
      sym_hex_unsigned_integer,
  [320] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(49), 1,
      anon_sym_0,
    ACTIONS(51), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(57), 1,
      anon_sym_DASH,
    STATE(46), 1,
      sym__dec_lit,
    STATE(47), 1,
      sym_float_lit,
    STATE(54), 1,
      sym__hex_int,
    STATE(60), 1,
      sym__dec_int,
    STATE(61), 1,
      sym__float,
    STATE(63), 1,
      sym__ident,
    STATE(65), 1,
      sym__oct_int,
    STATE(151), 1,
      sym_scalar_value,
    STATE(8), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    STATE(62), 10,
      sym_identifier,
      sym_string,
      sym_float,
      sym_signed_identifier,
      sym_dec_signed_integer,
      sym_oct_signed_integer,
      sym_hex_signed_integer,
      sym_dec_unsigned_integer,
      sym_oct_unsigned_integer,
      sym_hex_unsigned_integer,
  [387] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym__letter,
    ACTIONS(63), 1,
      sym__dec,
    STATE(10), 1,
      aux_sym__dec_lit_repeat1,
    STATE(40), 1,
      sym__exp,
    ACTIONS(67), 2,
      anon_sym_E,
      anon_sym_e,
    ACTIONS(65), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [416] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    STATE(9), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    ACTIONS(69), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [441] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_SQUOTE,
    ACTIONS(76), 1,
      anon_sym_DQUOTE,
    STATE(9), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    ACTIONS(71), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [466] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym__letter,
    ACTIONS(81), 1,
      sym__dec,
    STATE(10), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(84), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
      anon_sym_E,
      anon_sym_e,
  [491] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym__letter,
    ACTIONS(88), 1,
      sym__oct,
    STATE(48), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(90), 2,
      anon_sym_X,
      anon_sym_x,
    ACTIONS(92), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [517] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      sym__letter,
    ACTIONS(94), 1,
      sym__dec,
    STATE(25), 1,
      aux_sym__dec_lit_repeat1,
    STATE(71), 1,
      sym__exp,
    ACTIONS(96), 2,
      anon_sym_E,
      anon_sym_e,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [545] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      sym__letter,
    ACTIONS(101), 1,
      anon_sym_LBRACK,
    STATE(81), 1,
      sym_field_name,
    ACTIONS(104), 2,
      anon_sym_RBRACE,
      anon_sym_GT,
    STATE(118), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(13), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [573] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 12,
      sym__letter,
      anon_sym_COLON,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_DOT,
  [591] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(31), 1,
      anon_sym_0,
    ACTIONS(33), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(45), 1,
      anon_sym_DOT,
    STATE(46), 1,
      sym__dec_lit,
    STATE(47), 1,
      sym_float_lit,
    STATE(55), 1,
      sym__hex_int,
    STATE(56), 1,
      sym__oct_int,
    STATE(64), 1,
      sym__ident,
    STATE(66), 1,
      sym__float,
    STATE(67), 1,
      sym__dec_int,
  [628] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    STATE(78), 1,
      sym_field_name,
    STATE(118), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(17), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [655] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      sym__letter,
    ACTIONS(101), 1,
      anon_sym_LBRACK,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    STATE(78), 1,
      sym_field_name,
    STATE(118), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(17), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [682] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(110), 1,
      anon_sym_GT,
    STATE(81), 1,
      sym_field_name,
    STATE(118), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(26), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [709] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      sym_field_name,
    STATE(118), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(24), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [736] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_SQUOTE,
    ACTIONS(115), 1,
      anon_sym_DQUOTE,
    STATE(20), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    ACTIONS(71), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [759] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(20), 4,
      sym__single_string,
      sym__double_string,
      sym__string,
      aux_sym_string_repeat1,
    ACTIONS(69), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [782] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym__letter,
    ACTIONS(118), 1,
      sym__oct,
    STATE(57), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(120), 2,
      anon_sym_X,
      anon_sym_x,
    ACTIONS(92), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [807] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      sym_field_name,
    STATE(118), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(29), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [834] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      sym_field_name,
    STATE(118), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(13), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [861] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym__letter,
    ACTIONS(126), 1,
      sym__dec,
    STATE(25), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(84), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
      anon_sym_E,
      anon_sym_e,
  [884] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(124), 1,
      anon_sym_GT,
    STATE(81), 1,
      sym_field_name,
    STATE(118), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(13), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [911] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      anon_sym_GT,
    STATE(81), 1,
      sym_field_name,
    STATE(118), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(13), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [938] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__letter,
    ACTIONS(13), 1,
      anon_sym_0,
    ACTIONS(15), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(27), 1,
      anon_sym_DOT,
    STATE(53), 1,
      sym__dec_lit,
    STATE(59), 1,
      sym_float_lit,
    STATE(92), 1,
      sym__dec_int,
    STATE(103), 1,
      sym__float,
    STATE(106), 1,
      sym__ident,
    STATE(107), 1,
      sym__hex_int,
    STATE(108), 1,
      sym__oct_int,
  [975] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      sym_field_name,
    STATE(118), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(13), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [1002] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(49), 1,
      anon_sym_0,
    ACTIONS(51), 1,
      aux_sym__dec_lit_token1,
    ACTIONS(55), 1,
      anon_sym_DOT,
    STATE(46), 1,
      sym__dec_lit,
    STATE(47), 1,
      sym_float_lit,
    STATE(55), 1,
      sym__hex_int,
    STATE(56), 1,
      sym__oct_int,
    STATE(64), 1,
      sym__ident,
    STATE(66), 1,
      sym__float,
    STATE(67), 1,
      sym__dec_int,
  [1039] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(122), 1,
      anon_sym_GT,
    STATE(81), 1,
      sym_field_name,
    STATE(118), 3,
      sym__ident,
      sym_extension_name,
      sym_any_name,
    STATE(27), 4,
      sym_scalar_field,
      sym__field,
      sym_message_field,
      aux_sym_source_file_repeat1,
  [1066] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym__letter,
    ACTIONS(131), 1,
      sym__dec,
    STATE(34), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(92), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [1088] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym__letter,
    ACTIONS(133), 1,
      sym__dec,
    STATE(33), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(84), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [1110] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      sym__letter,
    ACTIONS(138), 1,
      sym__dec,
    STATE(33), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(140), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [1132] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      sym__dec,
    ACTIONS(142), 1,
      sym__letter,
    STATE(33), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(144), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [1154] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      sym__dec,
    ACTIONS(146), 1,
      sym__letter,
    STATE(33), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(148), 7,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [1176] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 9,
      sym__letter,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1191] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym__dec,
    STATE(10), 1,
      aux_sym__dec_lit_repeat1,
    STATE(40), 1,
      sym__exp,
    ACTIONS(152), 2,
      anon_sym_E,
      anon_sym_e,
    ACTIONS(65), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_F,
      anon_sym_f,
  [1214] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym__letter,
    ACTIONS(154), 1,
      sym__dec,
    STATE(49), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(92), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [1235] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym__letter,
    ACTIONS(158), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
      anon_sym_F,
      anon_sym_f,
  [1252] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 9,
      sym__letter,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1267] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      sym__letter,
    ACTIONS(162), 1,
      sym__dec,
    STATE(45), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(148), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [1288] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      sym__oct,
    STATE(43), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(164), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1307] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      sym__letter,
    ACTIONS(162), 1,
      sym__dec,
    STATE(45), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(144), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [1328] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym__letter,
    ACTIONS(169), 1,
      sym__dec,
    STATE(45), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(84), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [1349] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      sym__letter,
    ACTIONS(176), 2,
      anon_sym_F,
      anon_sym_f,
    ACTIONS(174), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1368] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym__letter,
    ACTIONS(176), 2,
      anon_sym_F,
      anon_sym_f,
    ACTIONS(180), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1387] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      sym__oct,
    STATE(43), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(182), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1406] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      sym__letter,
    ACTIONS(162), 1,
      sym__dec,
    STATE(45), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(140), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [1427] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      sym__hex,
    STATE(50), 1,
      aux_sym__hex_int_repeat1,
    ACTIONS(186), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1445] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      sym__hex,
    STATE(50), 1,
      aux_sym__hex_int_repeat1,
    ACTIONS(191), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1463] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym__oct,
    STATE(48), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(195), 2,
      anon_sym_X,
      anon_sym_x,
    ACTIONS(92), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_F,
      anon_sym_f,
  [1483] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      sym__letter,
    ACTIONS(197), 2,
      anon_sym_F,
      anon_sym_f,
    ACTIONS(174), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1513] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1526] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1539] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym__oct,
    STATE(75), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(182), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1556] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1569] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym__letter,
    ACTIONS(197), 2,
      anon_sym_F,
      anon_sym_f,
    ACTIONS(180), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1599] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1612] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1625] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1638] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1651] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1664] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1677] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1690] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1703] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 7,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1716] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 7,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1729] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      sym__letter,
    ACTIONS(158), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_F,
      anon_sym_f,
  [1744] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 7,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1757] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym__hex,
    STATE(73), 1,
      aux_sym__hex_int_repeat1,
    ACTIONS(186), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1774] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym__hex,
    STATE(73), 1,
      aux_sym__hex_int_repeat1,
    ACTIONS(191), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1791] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym__oct,
    STATE(75), 1,
      aux_sym__oct_int_repeat1,
    ACTIONS(164), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [1808] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym__dec,
    STATE(10), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(144), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_F,
      anon_sym_f,
  [1824] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1836] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LT,
    ACTIONS(239), 1,
      anon_sym_COLON,
    ACTIONS(241), 1,
      anon_sym_LBRACK,
    STATE(114), 2,
      sym_message_list,
      sym_message_value,
  [1856] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym__dec,
    STATE(10), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(140), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_F,
      anon_sym_f,
  [1872] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1884] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(245), 1,
      anon_sym_COLON,
    ACTIONS(247), 1,
      anon_sym_LBRACK,
    STATE(87), 2,
      sym_message_list,
      sym_message_value,
  [1904] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1916] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(251), 4,
      sym__letter,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1930] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(255), 4,
      sym__letter,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1944] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym__dec,
    STATE(79), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(92), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_F,
      anon_sym_f,
  [1960] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1972] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(263), 4,
      sym__letter,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [1986] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym__dec,
    STATE(10), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(148), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_F,
      anon_sym_f,
  [2002] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [2014] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 6,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [2026] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2037] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2048] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2059] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2070] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2081] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2092] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2103] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2114] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2125] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2136] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2147] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2169] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2180] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(251), 3,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_LBRACK,
  [2193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2204] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2215] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2226] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2237] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(255), 3,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_LBRACK,
  [2250] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2261] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 5,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
  [2283] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(263), 3,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_LBRACK,
  [2296] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 4,
      sym__letter,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [2306] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      sym__hex,
    STATE(116), 1,
      aux_sym__hex_int_repeat1,
    ACTIONS(186), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2320] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    STATE(120), 1,
      sym__ident,
    STATE(162), 1,
      sym_domain,
    STATE(164), 1,
      sym_type_name,
  [2336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 4,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT,
  [2346] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      sym__dec,
    STATE(36), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(286), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [2360] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_RBRACK,
    ACTIONS(290), 1,
      anon_sym_SLASH,
    ACTIONS(292), 1,
      anon_sym_DOT,
    STATE(125), 1,
      aux_sym_type_name_repeat1,
  [2376] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_DOT,
    STATE(121), 1,
      aux_sym_type_name_repeat1,
    ACTIONS(294), 2,
      anon_sym_RBRACK,
      anon_sym_SLASH,
  [2390] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(299), 1,
      anon_sym_RBRACK,
    STATE(133), 1,
      sym_message_value,
  [2406] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 4,
      sym__letter,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [2416] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 4,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT,
  [2426] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_DOT,
    ACTIONS(305), 1,
      anon_sym_RBRACK,
    ACTIONS(307), 1,
      anon_sym_SLASH,
    STATE(121), 1,
      aux_sym_type_name_repeat1,
  [2442] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 4,
      sym__letter,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
      anon_sym_GT,
  [2452] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 4,
      anon_sym_COLON,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT,
  [2462] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      sym__hex,
    STATE(116), 1,
      aux_sym__hex_int_repeat1,
    ACTIONS(191), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2476] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(313), 1,
      anon_sym_RBRACK,
    STATE(146), 1,
      sym_message_value,
  [2492] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      sym__dec,
    STATE(42), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(317), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [2506] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      sym__dec,
    STATE(88), 1,
      aux_sym__dec_lit_repeat1,
    ACTIONS(321), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
  [2520] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    ACTIONS(325), 1,
      anon_sym_RBRACK,
    STATE(143), 1,
      aux_sym_message_list_repeat1,
  [2533] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    ACTIONS(327), 1,
      anon_sym_RBRACK,
    STATE(144), 1,
      aux_sym_message_list_repeat1,
  [2546] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 3,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_LBRACK,
  [2555] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_DOT,
    ACTIONS(305), 1,
      anon_sym_RBRACK,
    STATE(121), 1,
      aux_sym_type_name_repeat1,
  [2568] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 3,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_LBRACK,
  [2577] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      anon_sym_LT,
    STATE(156), 1,
      sym_message_value,
  [2590] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_RBRACK,
    ACTIONS(292), 1,
      anon_sym_DOT,
    STATE(135), 1,
      aux_sym_type_name_repeat1,
  [2603] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 3,
      anon_sym_RBRACK,
      anon_sym_SLASH,
      anon_sym_DOT,
  [2612] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_COMMA,
    ACTIONS(331), 1,
      anon_sym_RBRACK,
    STATE(141), 1,
      aux_sym_scalar_list_repeat1,
  [2625] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_COMMA,
    ACTIONS(336), 1,
      anon_sym_RBRACK,
    STATE(141), 1,
      aux_sym_scalar_list_repeat1,
  [2638] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_COMMA,
    ACTIONS(338), 1,
      anon_sym_RBRACK,
    STATE(140), 1,
      aux_sym_scalar_list_repeat1,
  [2651] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      anon_sym_COMMA,
    ACTIONS(343), 1,
      anon_sym_RBRACK,
    STATE(143), 1,
      aux_sym_message_list_repeat1,
  [2664] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    ACTIONS(345), 1,
      anon_sym_RBRACK,
    STATE(143), 1,
      aux_sym_message_list_repeat1,
  [2677] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 3,
      ts_builtin_sym_end,
      sym__letter,
      anon_sym_LBRACK,
  [2686] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    ACTIONS(347), 1,
      anon_sym_RBRACK,
    STATE(132), 1,
      aux_sym_message_list_repeat1,
  [2699] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_COMMA,
    ACTIONS(349), 1,
      anon_sym_RBRACK,
    STATE(141), 1,
      aux_sym_scalar_list_repeat1,
  [2712] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    STATE(138), 1,
      sym__ident,
    STATE(169), 1,
      sym_type_name,
  [2725] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_COMMA,
    ACTIONS(351), 1,
      anon_sym_RBRACK,
    STATE(147), 1,
      aux_sym_scalar_list_repeat1,
  [2738] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      sym__dec,
    STATE(38), 1,
      aux_sym__dec_lit_repeat1,
  [2748] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2756] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym__letter,
    STATE(139), 1,
      sym__ident,
  [2766] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      sym__dec,
    STATE(12), 1,
      aux_sym__dec_lit_repeat1,
  [2776] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      sym__dec,
    STATE(7), 1,
      aux_sym__dec_lit_repeat1,
  [2786] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      sym__hex,
    STATE(74), 1,
      aux_sym__hex_int_repeat1,
  [2796] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      sym__hex,
    STATE(128), 1,
      aux_sym__hex_int_repeat1,
  [2814] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      sym__hex,
    STATE(51), 1,
      aux_sym__hex_int_repeat1,
  [2824] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      sym__dec,
    STATE(35), 1,
      aux_sym__dec_lit_repeat1,
  [2834] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      sym__dec,
    STATE(44), 1,
      aux_sym__dec_lit_repeat1,
  [2844] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      sym__dec,
    STATE(76), 1,
      aux_sym__dec_lit_repeat1,
  [2854] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      anon_sym_SLASH,
  [2861] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      anon_sym_SQUOTE,
  [2868] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      anon_sym_RBRACK,
  [2875] = 2,
    ACTIONS(377), 1,
      aux_sym__double_string_token1,
    ACTIONS(379), 1,
      sym_comment,
  [2882] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 1,
      anon_sym_DQUOTE,
  [2889] = 2,
    ACTIONS(379), 1,
      sym_comment,
    ACTIONS(383), 1,
      aux_sym__single_string_token1,
  [2896] = 2,
    ACTIONS(379), 1,
      sym_comment,
    ACTIONS(385), 1,
      aux_sym__ident_token1,
  [2903] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(387), 1,
      anon_sym_RBRACK,
  [2910] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(389), 1,
      anon_sym_DQUOTE,
  [2917] = 2,
    ACTIONS(379), 1,
      sym_comment,
    ACTIONS(391), 1,
      aux_sym__single_string_token1,
  [2924] = 2,
    ACTIONS(379), 1,
      sym_comment,
    ACTIONS(393), 1,
      aux_sym__double_string_token1,
  [2931] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 1,
      ts_builtin_sym_end,
  [2938] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(397), 1,
      anon_sym_SQUOTE,
  [2945] = 2,
    ACTIONS(379), 1,
      sym_comment,
    ACTIONS(399), 1,
      aux_sym__ident_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 81,
  [SMALL_STATE(4)] = 162,
  [SMALL_STATE(5)] = 241,
  [SMALL_STATE(6)] = 320,
  [SMALL_STATE(7)] = 387,
  [SMALL_STATE(8)] = 416,
  [SMALL_STATE(9)] = 441,
  [SMALL_STATE(10)] = 466,
  [SMALL_STATE(11)] = 491,
  [SMALL_STATE(12)] = 517,
  [SMALL_STATE(13)] = 545,
  [SMALL_STATE(14)] = 573,
  [SMALL_STATE(15)] = 591,
  [SMALL_STATE(16)] = 628,
  [SMALL_STATE(17)] = 655,
  [SMALL_STATE(18)] = 682,
  [SMALL_STATE(19)] = 709,
  [SMALL_STATE(20)] = 736,
  [SMALL_STATE(21)] = 759,
  [SMALL_STATE(22)] = 782,
  [SMALL_STATE(23)] = 807,
  [SMALL_STATE(24)] = 834,
  [SMALL_STATE(25)] = 861,
  [SMALL_STATE(26)] = 884,
  [SMALL_STATE(27)] = 911,
  [SMALL_STATE(28)] = 938,
  [SMALL_STATE(29)] = 975,
  [SMALL_STATE(30)] = 1002,
  [SMALL_STATE(31)] = 1039,
  [SMALL_STATE(32)] = 1066,
  [SMALL_STATE(33)] = 1088,
  [SMALL_STATE(34)] = 1110,
  [SMALL_STATE(35)] = 1132,
  [SMALL_STATE(36)] = 1154,
  [SMALL_STATE(37)] = 1176,
  [SMALL_STATE(38)] = 1191,
  [SMALL_STATE(39)] = 1214,
  [SMALL_STATE(40)] = 1235,
  [SMALL_STATE(41)] = 1252,
  [SMALL_STATE(42)] = 1267,
  [SMALL_STATE(43)] = 1288,
  [SMALL_STATE(44)] = 1307,
  [SMALL_STATE(45)] = 1328,
  [SMALL_STATE(46)] = 1349,
  [SMALL_STATE(47)] = 1368,
  [SMALL_STATE(48)] = 1387,
  [SMALL_STATE(49)] = 1406,
  [SMALL_STATE(50)] = 1427,
  [SMALL_STATE(51)] = 1445,
  [SMALL_STATE(52)] = 1463,
  [SMALL_STATE(53)] = 1483,
  [SMALL_STATE(54)] = 1500,
  [SMALL_STATE(55)] = 1513,
  [SMALL_STATE(56)] = 1526,
  [SMALL_STATE(57)] = 1539,
  [SMALL_STATE(58)] = 1556,
  [SMALL_STATE(59)] = 1569,
  [SMALL_STATE(60)] = 1586,
  [SMALL_STATE(61)] = 1599,
  [SMALL_STATE(62)] = 1612,
  [SMALL_STATE(63)] = 1625,
  [SMALL_STATE(64)] = 1638,
  [SMALL_STATE(65)] = 1651,
  [SMALL_STATE(66)] = 1664,
  [SMALL_STATE(67)] = 1677,
  [SMALL_STATE(68)] = 1690,
  [SMALL_STATE(69)] = 1703,
  [SMALL_STATE(70)] = 1716,
  [SMALL_STATE(71)] = 1729,
  [SMALL_STATE(72)] = 1744,
  [SMALL_STATE(73)] = 1757,
  [SMALL_STATE(74)] = 1774,
  [SMALL_STATE(75)] = 1791,
  [SMALL_STATE(76)] = 1808,
  [SMALL_STATE(77)] = 1824,
  [SMALL_STATE(78)] = 1836,
  [SMALL_STATE(79)] = 1856,
  [SMALL_STATE(80)] = 1872,
  [SMALL_STATE(81)] = 1884,
  [SMALL_STATE(82)] = 1904,
  [SMALL_STATE(83)] = 1916,
  [SMALL_STATE(84)] = 1930,
  [SMALL_STATE(85)] = 1944,
  [SMALL_STATE(86)] = 1960,
  [SMALL_STATE(87)] = 1972,
  [SMALL_STATE(88)] = 1986,
  [SMALL_STATE(89)] = 2002,
  [SMALL_STATE(90)] = 2014,
  [SMALL_STATE(91)] = 2026,
  [SMALL_STATE(92)] = 2037,
  [SMALL_STATE(93)] = 2048,
  [SMALL_STATE(94)] = 2059,
  [SMALL_STATE(95)] = 2070,
  [SMALL_STATE(96)] = 2081,
  [SMALL_STATE(97)] = 2092,
  [SMALL_STATE(98)] = 2103,
  [SMALL_STATE(99)] = 2114,
  [SMALL_STATE(100)] = 2125,
  [SMALL_STATE(101)] = 2136,
  [SMALL_STATE(102)] = 2147,
  [SMALL_STATE(103)] = 2158,
  [SMALL_STATE(104)] = 2169,
  [SMALL_STATE(105)] = 2180,
  [SMALL_STATE(106)] = 2193,
  [SMALL_STATE(107)] = 2204,
  [SMALL_STATE(108)] = 2215,
  [SMALL_STATE(109)] = 2226,
  [SMALL_STATE(110)] = 2237,
  [SMALL_STATE(111)] = 2250,
  [SMALL_STATE(112)] = 2261,
  [SMALL_STATE(113)] = 2272,
  [SMALL_STATE(114)] = 2283,
  [SMALL_STATE(115)] = 2296,
  [SMALL_STATE(116)] = 2306,
  [SMALL_STATE(117)] = 2320,
  [SMALL_STATE(118)] = 2336,
  [SMALL_STATE(119)] = 2346,
  [SMALL_STATE(120)] = 2360,
  [SMALL_STATE(121)] = 2376,
  [SMALL_STATE(122)] = 2390,
  [SMALL_STATE(123)] = 2406,
  [SMALL_STATE(124)] = 2416,
  [SMALL_STATE(125)] = 2426,
  [SMALL_STATE(126)] = 2442,
  [SMALL_STATE(127)] = 2452,
  [SMALL_STATE(128)] = 2462,
  [SMALL_STATE(129)] = 2476,
  [SMALL_STATE(130)] = 2492,
  [SMALL_STATE(131)] = 2506,
  [SMALL_STATE(132)] = 2520,
  [SMALL_STATE(133)] = 2533,
  [SMALL_STATE(134)] = 2546,
  [SMALL_STATE(135)] = 2555,
  [SMALL_STATE(136)] = 2568,
  [SMALL_STATE(137)] = 2577,
  [SMALL_STATE(138)] = 2590,
  [SMALL_STATE(139)] = 2603,
  [SMALL_STATE(140)] = 2612,
  [SMALL_STATE(141)] = 2625,
  [SMALL_STATE(142)] = 2638,
  [SMALL_STATE(143)] = 2651,
  [SMALL_STATE(144)] = 2664,
  [SMALL_STATE(145)] = 2677,
  [SMALL_STATE(146)] = 2686,
  [SMALL_STATE(147)] = 2699,
  [SMALL_STATE(148)] = 2712,
  [SMALL_STATE(149)] = 2725,
  [SMALL_STATE(150)] = 2738,
  [SMALL_STATE(151)] = 2748,
  [SMALL_STATE(152)] = 2756,
  [SMALL_STATE(153)] = 2766,
  [SMALL_STATE(154)] = 2776,
  [SMALL_STATE(155)] = 2786,
  [SMALL_STATE(156)] = 2796,
  [SMALL_STATE(157)] = 2804,
  [SMALL_STATE(158)] = 2814,
  [SMALL_STATE(159)] = 2824,
  [SMALL_STATE(160)] = 2834,
  [SMALL_STATE(161)] = 2844,
  [SMALL_STATE(162)] = 2854,
  [SMALL_STATE(163)] = 2861,
  [SMALL_STATE(164)] = 2868,
  [SMALL_STATE(165)] = 2875,
  [SMALL_STATE(166)] = 2882,
  [SMALL_STATE(167)] = 2889,
  [SMALL_STATE(168)] = 2896,
  [SMALL_STATE(169)] = 2903,
  [SMALL_STATE(170)] = 2910,
  [SMALL_STATE(171)] = 2917,
  [SMALL_STATE(172)] = 2924,
  [SMALL_STATE(173)] = 2931,
  [SMALL_STATE(174)] = 2938,
  [SMALL_STATE(175)] = 2945,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(168),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(175),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(167),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(165),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(171),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(172),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float_lit, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_lit, 2),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(171),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(172),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__dec_lit_repeat1, 2),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__dec_lit_repeat1, 2), SHIFT_REPEAT(10),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__dec_lit_repeat1, 2),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dec_lit, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dec_lit, 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(168),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(117),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ident, 2),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(167),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(165),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(155),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__dec_lit_repeat1, 2), SHIFT_REPEAT(25),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__dec_lit_repeat1, 2), SHIFT_REPEAT(33),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dec_lit, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dec_lit, 2),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exp, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 3),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exp, 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 2),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__double_string, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float_lit, 3),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_lit, 3),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__single_string, 3),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__oct_int_repeat1, 2),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__oct_int_repeat1, 2), SHIFT_REPEAT(43),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__dec_lit_repeat1, 2), SHIFT_REPEAT(45),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__dec_int, 1),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__dec_int, 1),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__float, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__oct_int, 2),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__hex_int_repeat1, 2),
  [188] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__hex_int_repeat1, 2), SHIFT_REPEAT(50),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex_int, 3),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(157),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hex_unsigned_integer, 1),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hex_signed_integer, 2),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_oct_signed_integer, 2),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_value, 2),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dec_unsigned_integer, 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_value, 1),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signed_identifier, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_oct_unsigned_integer, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 2),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dec_signed_integer, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_value, 3),
  [229] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__hex_int_repeat1, 2), SHIFT_REPEAT(73),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__oct_int_repeat1, 2), SHIFT_REPEAT(75),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 4),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 3),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 2),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 3),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_field, 3),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_list, 2),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 2),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_list, 3),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_list, 4),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 4),
  [279] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__hex_int_repeat1, 2), SHIFT_REPEAT(116),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_name, 1),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 1),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 2),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 2), SHIFT_REPEAT(152),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_field, 4),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_any_name, 5),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 2),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 2),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension_name, 3),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [333] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scalar_list_repeat1, 2), SHIFT_REPEAT(6),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scalar_list_repeat1, 2),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [340] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_list_repeat1, 2), SHIFT_REPEAT(137),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_list_repeat1, 2),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [377] = {.entry = {.count = 1, .reusable = false}}, SHIFT(166),
  [379] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [383] = {.entry = {.count = 1, .reusable = false}}, SHIFT(163),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [391] = {.entry = {.count = 1, .reusable = false}}, SHIFT(174),
  [393] = {.entry = {.count = 1, .reusable = false}}, SHIFT(170),
  [395] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_textproto(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
